version: '3.6'

volumes:
  exec_data:

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - default
  forest-service:
    image: planqk/forest-service:latest
    command: sh /app/startup.sh
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    networks:
      - default

  rq-worker:
    image: planqk/forest-service:latest
    command: rq worker --url redis://redis forest-service_execute
    environment:
      - REDIS_URL=redis://redis
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    depends_on:
      - redis
    deploy:
      replicas: 4

  rigetti-qvm:
    image: rigetti/qvm
    ports:
      - "5666:5666"
    command: -S -p 5666

  forest-quilc:
    image: rigetti/quilc
    ports:
      - "5667:5667"
    command: -S -p 5667

networks:
  default:
    driver: bridge
