version: '3.6'

volumes:
  exec_data:

services:
  redis:
    image: redis:latest
    command: --port 5040
    ports:
      - "5040:5040"
    networks:
      - default
  forest-service:
    image: planqk/forest-service:latest
    command: sh /app/startup.sh
    ports:
      - "5014:5014"
    environment:
      - REDIS_URL=redis://redis:5040
      - DATABASE_URL=sqlite:////data/app.db
      - QVM_HOSTNAME=rigetti-qvm
      - QVM_PORT=5016
      - QUILC_HOSTNAME=rigetti-quilc
      - QUILC_PORT=5017
    volumes:
      - exec_data:/data
    networks:
      - default

  rq-worker:
    image: planqk/forest-service:latest
    command: rq worker --url redis://redis:5040 forest-service_execute
    environment:
      - REDIS_URL=redis://redis:5040
      - DATABASE_URL=sqlite:////data/app.db
      - QVM_HOSTNAME=rigetti-qvm
      - QVM_PORT=5016
      - QUILC_HOSTNAME=rigetti-quilc
      - QUILC_PORT=5017
    volumes:
      - exec_data:/data
    depends_on:
      - redis
    deploy:
      replicas: 4
    networks:
      - default

  rigetti-qvm:
    image: rigetti/qvm
    ports:
      - "5016:5016"
    command: -S -p 5016
    networks:
      - default

  rigetti-quilc:
    image: rigetti/quilc
    ports:
      - "5017:5017"
    command: -S -p 5017
    networks:
      - default

networks:
  default:
    driver: bridge
