"""empty message

Revision ID: c3d1f654f810
Revises: 9a97012f0394
Create Date: 2024-06-24 17:39:13.696560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d1f654f810'
down_revision = '9a97012f0394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_result_generated_circuit_id_generated__circuit'), 'generated__circuit', ['generated_circuit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_result_generated_circuit_id_generated__circuit'), type_='foreignkey')

    # ### end Alembic commands ###
